package me.sailex.secondbrain.command;

import me.sailex.secondbrain.SecondBrainPlugin;
import me.sailex.secondbrain.npc.NPCData;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabExecutor;
import org.bukkit.entity.Player;

import java.util.List;

/** Handles clickable approve/deny/yes/no buttons generated by NPCActions. */
public class ActionCommand implements TabExecutor {

    private final SecondBrainPlugin plugin;
    public ActionCommand(SecondBrainPlugin plugin) { this.plugin = plugin; }

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        if (!(sender instanceof Player p)) {
            sender.sendMessage("\u00a7cOnly players can click these buttons.");
            return true;
        }
        if (args.length < 2) return true;
        NPCData npc = plugin.getNpcManager().findById(args[0]);
        if (npc == null) {
            p.sendMessage("\u00a7cThat NPC is no longer active.");
            return true;
        }
        switch (args[1].toLowerCase()) {
            case "approve" -> {
                if (!plugin.getNpcActions().approve(p, npc))
                    p.sendMessage("\u00a7cNo pending approval for that NPC, or it isn't yours.");
            }
            case "deny" -> plugin.getNpcActions().deny(p, npc);
            case "yes", "y" -> plugin.getNpcActions().answer(p, npc, true);
            case "no", "n" -> plugin.getNpcActions().answer(p, npc, false);
        }
        return true;
    }

    @Override public List<String> onTabComplete(CommandSender s, Command c, String a, String[] args) {
        return List.of();
    }
}
